# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./Prizm.RePack/Prizm.RePack.csproj
    - name: Build
      run: dotnet build ./Prizm.RePack/Prizm.RePack.csproj --configuration Release --no-restore 
    - name: Publish
      run: dotnet publish ./Prizm.RePack/Prizm.RePack.csproj --configuration Release --build --output ./publish
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: ./publish/repack-webp.exe
